### ISSUE TITLE
环境搭建失败

### ISSUE THREAD

**Issue by dysf888** [15127188821/AntSignIn#1]
尝试了各种php版本，和各种杂七杂八的配置，使用宝塔面板管理，一直有神仙报错，不知大佬可否分享详细配置过程（后端）

**Comment by wtmb** [comment]
> 试用了各种php版本，和各种杂七杂八的配置，使用宝塔面板管理，一直有神仙报错，不知大佬可否详细配置过程（完整过程）

兄弟，你解决了嘛

**Comment by dysf888** [comment]
> > 试用了各种php版本，和各种杂七杂八的配置，使用宝塔面板管理，一直有神仙报错，不知大佬可否详细配置过程（完整过程）
> 
> 兄弟，你解决了嘛

没有哇=，=

**Comment by wtmb** [comment]
> > > 试用了各种php版本，和各种杂七杂八的配置，使用宝塔面板管理，一直有神仙报错，不知大佬可否详细配置过程（完整过程）
> > 
> > 
> > 兄弟，你解决了嘛
> 
> 没有哇=，=

你报的啥错

**Comment by wtmb** [comment]
是SQLSTATE[HY000] [2002] No route to host这个嘛

**Comment by wtmb** [comment]
> > 试用了各种php版本，和各种杂七杂八的配置，使用宝塔面板管理，一直有神仙报错，不知大佬可否详细配置过程（完整过程）
> 
> 兄弟，你解决了嘛

我跑起来了，不过这个功能不是太完整要自己完善
